### ISSUE TITLE
`pks check` does not fail on architecture violations

### ISSUE THREAD

**Issue by professor** [alexevanczuk/packs#120]
Here's an example:
https://github.com/professor/packs-architecture-violation

`pks update` successfully generates this `package_todo.yml`:
```
packs/domain_pack:
  "::Domain":
    violations:
    - architecture
    - privacy
    files:
    - packs/utility_pack/app/models/utility.rb
```

However, `pks check` reports `No violations detected!` when `enforce_architecture: strict`

`bin/packwerk check` and `bin/packwerk validate` both correctly fail.
